project:
  type: website
  output-dir: _output

website:
  title: 'Quarto Review Example'
  navbar:
    left:
      - text: 'Home'
        file: document.qmd
      - text: 'Debug'
        file: debug-example.qmd
      - text: 'Translation'
        file: doc-translation.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

review:
  enabled: true
  debug:
    enabled: true
    level: debug
    modules:
      - UIModule
      - ChangesModule
filters:
  - review
